### ISSUE TITLE
Find Longest Binary Gap

### ISSUE THREAD

**Issue by AlgusDark** [Tequila-js/katas#10]
A binary gap within a positive integer **N** is any maximal sequence of consecutive zeros that is surrounded by ones at both ends in the binary representation of **N**.

For example, number `9` has binary representation `1001` and contains a binary gap of length `2`. The number `529` has binary representation `1000010001` and contains two binary gaps: one of length `4` and one of length `3`. The number `20` has binary representation `10100` and contains one binary gap of length `1`. The number `15` has binary representation `1111` and has no binary gaps.

Given a positive integer **N**, returns the length of its longest binary gap. The function should return _0_ if **N** doesn't contain a binary gap.

**Comment by ruberuvalcaba** [comment]
function bin(n){
  var nBin = (n >>> 0).toString(2);
  var arrBin = nBin.split('1');
  var len = arrBin.length;
  var max = 0;
  var maxLen = 0;
  var even = n % 2;
  
  for(i = 0; i < len; i ++){
    maxLen = arrBin[i].length;
    if(maxLen > max && even !== 0){
      max = maxLen;
    }
  }
  return max;
}

bin(529);
