### ISSUE TITLE
Valid Anagram

### ISSUE THREAD

**Issue by AlgusDark** [Tequila-js/katas#3]
Given two strings s and t, write a function to determine if t is an anagram of s.

**For example**:
s = "anagram", t = "nagaram", return true.
s = "rat", t = "car", return false.

**Note**:
You may assume the string contains only lowercase alphabets.

**Comment by MDOR** [comment]
```
function validAnagram(ini = '', sec = '') {
  let [initial, anagram, obj] = [ini.split(''), sec.split(''), {}];
      
  if (initial.length !== anagram.length) return false;

  for (let pos = initial.length - 1; pos >= 0; --pos) {
    let current = initial[pos];
    obj[current]= !obj[current]? 1: obj[current] + 1;
  }

  for (let pos = anagram.length - 1; pos >= 0; --pos) {
    let current = anagram[pos];
    
    if (!obj[current]) {
      return false;
    } else {
      obj[current] -= 1;
    }
  }

  return true;
}
```
Les dejo los resultados comparando esta implementación contra la del ordenamiento

![image](https://cloud.githubusercontent.com/assets/7268268/23191530/bb1238e2-f863-11e6-94f7-e86bd2be8c41.png)

**Comment by AlgusDark** [comment]
I haven't done some tests, but this is my first implementation:

```
Array.prototype.countBy = function(fn) {
  return this.reduce((hash, item) => {
    const key = fn(item);
    return hash.set(key, hash.has(key) ?  hash.get(key) + 1 : 1);
  }, new Map());
}

var isAnagram = (s,t) => {
  const countLetters = (str) => str.split('').countBy(letter => letter);
  
  const first = countLetters(s);
  const second = countLetters(t);
  
  if(first.size != second.size) return false;
  
  for([key, value] of first) {
    if(!second.has(key) || value !== second.get(key)) return false;
  }
  
  return true
}
```

If ain't wrong, this is a `O(N)` solution (We're using only one Loop and a HashMap).

The other implementation was:

```
const isAnagram = (s, t) => {
  const first = s.split('').sort().join('');
  const second = t.split('').sort().join('');
  
  return first === second;
}
```

this one is using `sort()`, since we don't know which sorting algorithm is using, we can't be sure of the Big O complexity, but my guess is that this one is `(n log(n))`.


[You can check performance here](https://jsperf.com/anagram-sort-vs-anagram-map/1)
