### ISSUE TITLE
Isomorphic Strings

### ISSUE THREAD

**Issue by AlgusDark** [Tequila-js/katas#5]
Given two strings **s** and **t**, determine if they are isomorphic.

Two strings are isomorphic if the characters in **s** can be replaced to get **t**.

All occurrences of a character must be replaced with another character while preserving the order of characters. No two characters may map to the same character but a character may map to itself.

For example,
Given `"egg"`, `"add"`, return true.

Given `"foo"`, `"bar"`, return false.

Given `"paper"`, `"title"`, return true.

**Note**:
You may assume both s and t have the same length.

**Comment by jondeltoro** [comment]
function isIsomorphic(s='',t=''){
  let result = true;
  let dicc1 = new Map(),
      dicc2 = new Map();
  for(let i=0;i<s.length;i++){
    let c1 = s[i],
        c2 = t[i];
    if((!dicc1.has(c1) && !dicc2.has(c2)) || (dicc1.get(c1)===c2 && dicc2.get(c2)===c1)){
      dicc1.set(c1, c2);
      dicc2.set(c2, c1);
    } else {
      return false;
    }
  }
  return result;
}

**Comment by jondeltoro** [comment]
```javascript
function isIsomorphic(s='',t=''){
  let result = true;
  let dicc1 = new Map(),
      dicc2 = new Map();
  for(let i=0;i<s.length;i++){
    let c1 = s[i],
        c2 = t[i];
    if((!dicc1.has(c1) && !dicc2.has(c2)) || (dicc1.get(c1)===c2 && dicc2.get(c2)===c1)){
      dicc1.set(c1, c2);
      dicc2.set(c2, c1);
    }else{
      return false;
    }
  }
  return result;
}
```

**Comment by luisgerrarrdo** [comment]
```javascript
function isIsomorphic(s, t){
  let arr = Array(27).fill(null), pos = 0;
    
  for(let i=0; i<s.length; i++){
    pos = s[i].charCodeAt()-97;
    if(arr[pos]===null){ // nueva letra encontrada en s
      if(arr.indexOf(t[i])===-1){ // no está repetida en arr
        arr[pos] = t[i];
      }else{
        return false;
      }
    }else if(arr[pos]!==t[i]){
        return false;
    }
  }
  return true;
}
```
